FROM jetty:9-jdk8-eclipse-temurin
MAINTAINER michimau <mauro.michielon@eea.europa.eu>

ARG id
USER root
RUN apt-get -y update && \
    apt-get -y install vim \
    wget \
    sudo \
    zip

RUN wget https://files.titellus.net/geonetwork/eea-v4/eea-catalogues-$id.tar.gz -O eea-catalogues.tar.gz && \
    tar -xvzf eea-catalogues.tar.gz -C /

RUN rm -rf /var/lib/jetty/webapps/*  && \
    chown jetty:jetty /target /var/lib/jetty/webapps && \
    mkdir -p /catalogue-data && \
    chown -R jetty:jetty /catalogue-data

RUN unzip -o /target/catalogue.war -d /var/lib/jetty/webapps/catalogue

RUN chown -R jetty:jetty /var/lib/jetty/webapps


COPY docker-entrypoint.sh /

USER jetty

ENTRYPOINT ["/docker-entrypoint.sh"]

